### ISSUE TITLE
Update to Godot new plugin API

### ISSUE THREAD

**Issue by trollworkout** [TheHX/add_primitives#10]
just that please update

![screen shot 2016-05-24 at 10 57 33 pm](https://cloud.githubusercontent.com/assets/6987027/15526831/ee056e00-2202-11e6-892f-bb77bc4e6014.png)

**Comment by TheHX** [comment]
This plugin don't is compatible with Godot github version, the plugin still uses the old API, i'm still using this API because it's compatible with Godot stable versions, and probably i'll only update after Godot 2.1.
But it's a good Idea add this to the readme(Sorry i forgot to do that).

**Comment by TheHX** [comment]
I'll leave this open until the update to new Godot plugin API.
