### ISSUE TITLE
Retina Support

### ISSUE THREAD

**Issue by ComancheAk** [TheHX/add_primitives#11]
I've downloaded your plugin and it isn't suitable for retina displays. I made a quick fix, by changing constant DIALOG_SIZE at MeshDialog.gd

Maybe it will be good to add HDPI check into plugin.

Thank you!

Plugin after fix
<img width="1280" alt="2016-09-04 19 52 44" src="https://cloud.githubusercontent.com/assets/6551114/18232488/ab182c24-72e1-11e6-8733-6795ca35533b.png">

**Comment by TheHX** [comment]
I've pushed a fix, could you test it?

**Comment by ComancheAk** [comment]
Works fine! Thanks!
