### ISSUE TITLE
Error on Godot 2.1.2-stable 

### ISSUE THREAD

**Issue by allysonsouza** [TheHX/add_primitives#12]
Hi,

I've tried to install in Godot 2.1.2-stable but when I change to "active" status, they throw me an error:

`Unable to load addon script from path: 'res://addons/./Plugin.gd' Base Type is not EditorPlugin.`

What could be wrong?

**Comment by stawek** [comment]
Check if addon files are not added right into addons dir instead of enclosing everything in add_primitives
<pre>
├── addons
│   └── add_primitives
│       ├── LICENSE.md
│       ├── plugin.cfg
│       ├── Plugin.gd
│       ├── README.md
│       └── src
</pre>

**Comment by allysonsouza** [comment]
Thanks @stawek, it's exactly what happened, the files are ind addons root instead of add_primitives subfolder.
