### ISSUE TITLE
Add Primitives for Godot 1.1

### ISSUE THREAD

**Issue by yichen0831** [TheHX/add_primitives#7]
Used with Godot Engine v1.1.stable. When trying to turn on the Add Primitives plugin, it shows the error message:

    ERROR: GDScript::reload: Parse Error: Unexpected token: Identifier:signal
    At: /.godot/plugins/Add Primitives/AddPrimitivesPlugin.gd:92

It seems that the signal syntax is not recognized?

**Comment by TheHX** [comment]
@yichen0831 The current Add Primitives state only work with Godot github version. To fix this i will create a new branch for Godot v1.1.

**Comment by TheHX** [comment]
@yichen0831 Can you test the branch to see if everything is working?

**Comment by yichen0831** [comment]
The branch works like a charm with Godot 1.1.stable. Good job!

**Comment by TheHX** [comment]
Thanks, closing now.

Em Sáb, Ago 29, 2015 em 11:09 , yichen0831 <notifications@github.com> 
escreveu:
