### ISSUE TITLE
Make the repository root be the plugin directory

### ISSUE THREAD

**Issue by bdero** [TheHX/add_primitives#8]
By simply moving all of the contents of `Add Primitives` to the repository root, a couple of things happen:

* Installation is simplified to one step: `git clone https://github.com/TheHX/add_primitives ~/.godot/plugins`
* Updating the plugin is simplified to: `pushd ~/.godot/plugins/add_primitives; git pull; popd`

**Comment by TheHX** [comment]
I was thinking on doing this, by creating a better API to create primitives, that can be used both on editor and on runtime, and the plugin a separate part.
And this can make possible additions like UV mapping for all primitives and saving the primitive data(the primitive can be edited any time).

**Comment by TheHX** [comment]
I've moved the ```plugin.cfg``` to the repository root and now is much more simpler to install and update the plugin. Thanks for the suggestion!
