### ISSUE TITLE
Update installation instructions

### ISSUE THREAD

**Issue by DriNeo** [TheHX/add_primitives#9]
On Windows 8.1, Godot 2.0.2, I can't find the primitives. Maybe I did something wrong.

![addprim](https://cloud.githubusercontent.com/assets/12350741/14761966/f85ef6a2-096e-11e6-99ca-0a3f22666dd1.png)

The folder "add_primitives-master" is dezipped on this path: C:\Users\UserName\AppData\Roaming\Godot\plugins

**Comment by dmw99** [comment]
You did the same thing I did. You need to rename "add_primitives-master" to "add_primitives" (the relative path is hard-coded into the plugin). Would be good to update the install directions, since if you follow them literally things don't work right off.

**Comment by DriNeo** [comment]
Thanks your help resolved the problem.
I tried to rename the issue to something like " Folder must be renamed " but I probably don't have permission.
Impressive plugin anyway !

**Comment by TheHX** [comment]
I updated the manual installation instruction to:

> Download the repository ZIP, unpack in the Godot plugins folder on your OS and rename the
> add_primitives-master folder to add_primitives.
